// Copyright 2026 Geda
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Adds the Live Activity widget extension to the generated Xcode project.
//
// A Live Activity is drawn by a widget extension, which is a second binary
// inside the app -- and `ios/` here is generated by `expo prebuild` and not
// checked in, so the target has to be described in code rather than clicked
// into Xcode once. That is all this plugin is: the same target anyone would
// add by hand, written down so that it survives `prebuild --clean`.
//
// The sources live in `ios-extensions/GedaLiveActivity/`, next to the app
// rather than inside the generated folder, and are copied in on every
// prebuild. `GedaTransferAttributes.swift` comes from the native module and is
// compiled into *both* binaries: ActivityKit matches the app's activity to the
// widget's by the type's name, so the two declarations have to be the same
// text, and the only reliable way to guarantee that is one file.

const { withXcodeProject, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const TARGET_NAME = 'GedaLiveActivity';
const SOURCE_DIR = path.join('ios-extensions', TARGET_NAME);
const SHARED_SOURCES = [path.join('modules', 'geda-transfer', 'ios', 'GedaTransferAttributes.swift')];
const DEPLOYMENT_TARGET = '16.4';

/** Copies the extension's sources into the generated `ios/` folder. */
const withSources = (config) =>
  withDangerousMod(config, [
    'ios',
    async (mod) => {
      const from = path.join(mod.modRequest.projectRoot, SOURCE_DIR);
      const to = path.join(mod.modRequest.platformProjectRoot, TARGET_NAME);

      fs.rmSync(to, { recursive: true, force: true });
      fs.mkdirSync(to, { recursive: true });

      for (const entry of fs.readdirSync(from)) {
        fs.copyFileSync(path.join(from, entry), path.join(to, entry));
      }
      for (const shared of SHARED_SOURCES) {
        const source = path.join(mod.modRequest.projectRoot, shared);
        fs.copyFileSync(source, path.join(to, path.basename(source)));
      }
      return mod;
    },
  ]);

const withTarget = (config) =>
  withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const appBundleId = mod.ios?.bundleIdentifier;
    if (!appBundleId) {
      throw new Error('withLiveActivity: ios.bundleIdentifier must be set in app.json');
    }

    // Idempotent: prebuild without --clean runs the plugin over a project that
    // may already have the target, and a second copy of it does not fail
    // loudly -- it fails at code signing, much later, in a confusing way.
    if (project.pbxTargetByName(TARGET_NAME)) {
      return mod;
    }

    const bundleId = `${appBundleId}.${TARGET_NAME}`;
    const sources = fs
      .readdirSync(path.join(mod.modRequest.platformProjectRoot, TARGET_NAME))
      .filter((name) => name.endsWith('.swift'))
      .map((name) => `${TARGET_NAME}/${name}`);

    const group = project.addPbxGroup(
      [...sources, `${TARGET_NAME}/Info.plist`],
      TARGET_NAME,
      TARGET_NAME,
    );

    // Hang the group off the project's root group, so the files are visible
    // in Xcode's navigator rather than only in the build.
    const groups = project.hash.project.objects.PBXGroup;
    for (const key of Object.keys(groups)) {
      if (groups[key].name === undefined && groups[key].path === undefined && groups[key].children) {
        groups[key].children.push({ value: group.uuid, comment: TARGET_NAME });
        break;
      }
    }

    const target = project.addTarget(TARGET_NAME, 'app_extension', TARGET_NAME, bundleId);

    project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);
    project.addBuildPhase(
      ['SwiftUI.framework', 'WidgetKit.framework', 'ActivityKit.framework'],
      'PBXFrameworksBuildPhase',
      'Frameworks',
      target.uuid,
    );

    for (const source of sources) {
      project.addSourceFile(source, { target: target.uuid }, group.uuid);
    }

    // The extension is a folder inside the app bundle, and the app must be
    // told to put it there. Without this phase everything compiles and the
    // Live Activity simply never appears.
    const app = project.getFirstTarget();
    const phase = project.addBuildPhase(
      [],
      'PBXCopyFilesBuildPhase',
      'Embed App Extensions',
      app.uuid,
      'app_extension',
    );
    embed(project, phase, target);

    // `addTargetDependency` writes into these two sections and does nothing at
    // all -- silently, no error -- when they are absent, which they are in a
    // freshly generated project with only one target. Without the dependency
    // the app can be built before the extension exists, and the embed phase
    // then copies whatever the last build left behind.
    const objects = project.hash.project.objects;
    objects.PBXTargetDependency = objects.PBXTargetDependency ?? {};
    objects.PBXContainerItemProxy = objects.PBXContainerItemProxy ?? {};
    project.addTargetDependency(app.uuid, [target.uuid]);

    applyBuildSettings(project, target.uuid, bundleId, mod);

    return mod;
  });

/**
 * Puts the extension's *product* into the app's embed phase.
 *
 * Passing a filename to `addBuildPhase` instead would make a second file
 * reference that belongs to no group, which `xcodeproj` rejects when
 * CocoaPods later rewrites the project -- "no parent for object". The product
 * reference the target already owns is the thing to embed.
 */
function embed(project, phase, target) {
  const product = project.pbxNativeTargetSection()[target.uuid].productReference;
  const comment = `${TARGET_NAME}.appex in Embed App Extensions`;
  const uuid = project.generateUuid();

  project.hash.project.objects.PBXBuildFile[uuid] = {
    isa: 'PBXBuildFile',
    fileRef: product,
    fileRef_comment: `${TARGET_NAME}.appex`,
    settings: { ATTRIBUTES: ['RemoveHeadersOnCopy'] },
  };
  project.hash.project.objects.PBXBuildFile[`${uuid}_comment`] = comment;
  phase.buildPhase.files.push({ value: uuid, comment });
}

/**
 * The build settings Xcode writes when a widget extension is added by hand.
 *
 * `SKIP_INSTALL` is the one that bites: an extension left installable ends up
 * at the top level of the archive as well as inside the app, and App Store
 * Connect rejects the upload.
 */
function applyBuildSettings(project, targetUuid, bundleId, mod) {
  const configurations = project.pbxXCBuildConfigurationSection();
  const lists = project.pbxXCConfigurationList();
  const listKey = project.pbxNativeTargetSection()[targetUuid].buildConfigurationList;
  const wanted = new Set(
    lists[listKey].buildConfigurations.map((entry) => entry.value),
  );

  for (const key of Object.keys(configurations)) {
    if (key.endsWith('_comment') || !wanted.has(key)) continue;

    Object.assign(configurations[key].buildSettings, {
      CLANG_ENABLE_MODULES: 'YES',
      CODE_SIGN_STYLE: 'Automatic',
      CURRENT_PROJECT_VERSION: `"${mod.ios?.buildNumber ?? '1'}"`,
      GENERATE_INFOPLIST_FILE: 'NO',
      INFOPLIST_FILE: `"${TARGET_NAME}/Info.plist"`,
      IPHONEOS_DEPLOYMENT_TARGET: DEPLOYMENT_TARGET,
      LD_RUNPATH_SEARCH_PATHS:
        '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
      MARKETING_VERSION: `"${mod.version ?? '1.0.0'}"`,
      PRODUCT_BUNDLE_IDENTIFIER: `"${bundleId}"`,
      PRODUCT_NAME: `"${TARGET_NAME}"`,
      SKIP_INSTALL: 'YES',
      SWIFT_EMIT_LOC_STRINGS: 'YES',
      SWIFT_VERSION: '5.0',
      TARGETED_DEVICE_FAMILY: '"1,2"',
    });
  }
}

/** Live Activities are off unless the app says it has them. */
const withInfoPlist = (config) => {
  config.ios = config.ios ?? {};
  config.ios.infoPlist = { ...config.ios.infoPlist, NSSupportsLiveActivities: true };
  return config;
};

module.exports = function withLiveActivity(config) {
  return withTarget(withSources(withInfoPlist(config)));
};

module.exports.TARGET_NAME = TARGET_NAME;
