// Copyright 2026 Geda
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package icons carries the app's tray artwork.
//
// The files are generated by gen.go and committed, so that building the app
// needs nothing but a Go toolchain.
package icons

import (
	_ "embed"
	"runtime"
)

//go:embed tray_template.png
var trayTemplate []byte

//go:embed tray.png
var trayPNG []byte

//go:embed tray.ico
var trayICO []byte

// Tray returns the menu-bar or notification-area icon for this platform.
//
// macOS gets a template image -- black plus alpha -- which the system recolours
// for the menu bar's appearance; a coloured icon there is wrong in dark mode.
// Windows has no such convention and takes an .ico.
func Tray() []byte {
	switch runtime.GOOS {
	case "darwin":
		return trayTemplate
	case "windows":
		return trayICO
	default:
		return trayPNG
	}
}

// TrayTemplate reports whether Tray returned a macOS template image, which the
// tray library has to be told about separately.
func TrayTemplate() bool { return runtime.GOOS == "darwin" }
